# site properties and page defaults
title: AARC Lab
subtitle: AI, Autonomy, Resilience, Control Lab
description: University Research Lab focus on AI, Autonomy, Resilience, Control for Cyber-physical Systems
header: images/prius_platoon.png
footer: images/cover_picture.png
proofer: false

# site social media and other links
links:
  email: rahul.bhadani@uah.edu
  orcid: 0000-0002-7403-6458
  google-scholar: wykFPlYAAAAJ
  github: AARC-lab
  twitter: AARC-lab
  youtube: AARC-lab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles
  fonts_dir: fonts

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts
  - _papers

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
